[package]
name = "locale-ly"
version = "0.0.0"
edition = "2021"

[dependencies]
frontend = { path = "frontend" }


[workspace.dependencies]
lingual = { git = "https://github.com/Deepp0925/lingual.git" }
errors = { path = "errors" }
core = { path = "core" }


[workspace.package]
version = "0.0.0"

[workspace]
members = ["src-tauri", "core", "frontend", "errors"]
