[package]
name = "locale-ly"
version = "0.0.0"
edition = "2021"

[dependencies]
frontend = { path = "frontend" }


[workspace.package]
version = "0.0.0"

[workspace]
members = ["src-tauri", "core", "frontend"]
