[package]
name = "errors"
edition = "2021"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lingual = {workspace =true}
rust-i18n = {workspace =true}
